version: "3"

networks:
  kafka-network:
    driver: bridge

services:
  zookeeper-node-01:
    container_name: zookeeper-node-01
    image: 'bitnami/zookeeper:3.6'
    networks: 
      - kafka-network
    ports:
      - '2181:2181'
    volumes: 
      - ./zookeeper-config/zoo.cfg:/opt/bitnami/zookeeper/config/zoo.cfg
      - ./data/zookeeper:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-node-01:
    container_name: kafka-node-01
    image: 'bitnami/kafka:2.4.0'
    hostname: kafka-node-01
    networks: 
      - kafka-network
    ports: 
      - '9092:9092'
      - '9093:9093'
      - '5555:5555'
    volumes: 
      - './kafka-cofig/kafka-node-01/server.properties:/bitnami/kafka/config/server.properties'
      - './data/kafka-node-01:/bitnami/kafka'
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-node-01:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-node-01:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - JMX_PORT=5555
    depends_on:
      - zookeeper-node-01

  kafka-node-02:
    container_name: kafka-node-02
    image: 'bitnami/kafka:2.4.0'
    hostname: kafka-node-02
    networks: 
      - kafka-network
    ports: 
      - '9094:9094'
      - '9095:9095'
      - '6666:6666'
    volumes: 
      - './kafka-cofig/kafka-node-02/server.properties:/bitnami/kafka/config/server.properties'
      - './data/kafka-node-02:/bitnami/kafka'
    environment: 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-node-01:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9094,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-node-02:9094,EXTERNAL://localhost:9095
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - JMX_PORT=6666
    depends_on:
      - zookeeper-node-01

  kafka-manager:
    container_name: kafka-manager
    image: 'kafkamanager/kafka-manager:3.0.0.4'
    networks: 
      - kafka-network
    ports: 
      - '9000:9000'
    environment:
      - ZK_HOSTS=zookeeper-node-01
    depends_on:
      - zookeeper-node-01